### ISSUE TITLE
make easy to use

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/url#5]
Right now the workings of this injectable is very unclear. The API should be 
- [ ] streamlined
- [ ] documented
- [ ] provide default use cases

Main problem is that the values (path and query) are set set by two actors
- app
- browser

We want to create a bidirectional flow, where `app` can set url resulting in a `browser` value and `browser` can set url resulting in an `app` value. 
Right now this functionality is supported by using two separate observables, one for the `app` to manipulate, and one for the `browser`.

The current approach can also be improved with a clearer structure.

**Comment by jimdebeer** [comment]
before examples go for tests in tap
